config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get 'skis/evo-ii', to: redirect('skis/evo')
  resources :skis, only: [:show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/skis_controller.rb
class SkisController < ApplicationController

  def show
    @boat = params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = display_meta_tags site: "Think Kayaks in Europe", title: "Welcome", author: "Micky McDonald", description: "Think Kayaks and Surfskis in Europe", keywords: "surf ski kayak boat", reverse: true
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", media: "all"
    <!--[if lt IE 9]>
    = javascript_include_tag "html5shiv"
    <![endif]-->
    = csrf_meta_tags
    %link{ rel: "icon", type: "image/ico", href: image_path("favicon.png") }
    %meta(content='width=device-width, initial-scale=1' name='viewport')
  %body{ class: "#{controller.class.name.underscore.gsub("/", "_").gsub(/_controller\Z/, '')} _#{controller.action_name}" }

    #wrap

      %header
      .container
        .row
          .col-md-12
            %h1
              = link_to root_path do
                Think Kayak Europe

      = yield

    #footer
      .container
        = render 'layouts/footer'

app/views/skis/_ace.html.haml
%h3 Dimensions
%ul
  %li Length: 538 cm
  %li Width: 56 cm
  %li Capacity: 60 - 110 kg

%p
  At Think Kayak we always get to work on fun stuff, but this time we’ve super-sized it with the Ace. If three words could sum up this new craft it’s stable, fast, and fun!

%p
  At 56 cm wide the Ace is our most stable ski, but her sleek "swede" form means the Ace has the speed of a performance ski. The 538 cm length is highly maneuverable, great for exploring along the coast line, or linking waves when you find the wind at your back. The gunwale is low beside the seat, making remounts a snap should the need arise, and the integrated carry handle makes off the water handling a breeze. For big fun on the water, the Ace is for you!

%h3 Prices
= render "construction", title: "ace", code: 'S-105F', euros: 2695, type: :performance
= render "construction", title: "ace", code: 'S-105R', euros: 3195, type: :river
= render "construction", title: "ace", code: 'S-105K', euros: 3495, type: :elite
= render "construction", title: "ace", code: 'S-105U', euros: 4295, type: :ultimate

app/views/skis/_construction.html.haml
%section.construction{ class: type }
  %h3
    %code= code
  %p.price
    %span &euro;#{number_with_delimiter euros}
  %p.name
    %strong= type.to_s.titleize
    Construction
  %p.materials
    - case type
    - when :performance
      (Fiberglass, Coremat, Epoxy, Vacuum)
    - when :river
      (Kevlar, Carbon, Coremat, Epoxy, Vacuum)
    - when :elite
      (Kevlar, Carbon, Honeycomb, Epoxy, Vacuum)
    - when :ultimate
      (Carbon, Honeycomb, Epoxy, Vacuum)

app/views/skis/_evo.html.haml
%h3 Dimensions
%ul
  %li Length: 625 cm
  %li Width: 47 cm
  %li Capacity: 60 - 110 kg

%p The Evo has set the bench mark for all-around performance for more than a decade. Competitively fast, intermediate stability, and great comfort make the Evo the best choice for enthusiast racers and fitness paddlers alike.

%p Now in its third generation, the Evo has just the right amount of rocker to surf like a champ as well as great speed on the flats. The intermediate width of 47 cm gives that extra bit of stability to help out when conditions get difficult, but the narrow profile at the catch allows for a very efficient stroke. The seat retains its ideal ergonomics, but now has a lower hump to allow for improved leg drive and rotation.

%p Any waves that find their way into the footwell are quickly dealt with using the DeBrito bailer. When you’re looking for a competitive ski, but don’t want to deal with the demands of an elite ski, then the Evo is your answer!

%h3 Prices
= render "construction", title: "evo", code: 'S-101F', euros: 2695, type: :performance
= render "construction", title: "evo", code: 'S-101R', euros: 3195, type: :river
= render "construction", title: "evo", code: 'S-101K', euros: 3495, type: :elite
= render "construction", title: "evo", code: 'S-101U', euros: 4295, type: :ultimate

app/views/skis/_eze.html.haml
%h3 Dimensions
%ul
  %li Length: 518 cm
  %li Width: 51 cm
  %li Capacity: 45 - 85 kg

%p
  The Think Eze is the ideal boat for a lot of people. It's fast, fun, and sporty, with the soul of a racer, yet it's 518 x 51 cm dimensions make it maneuverable, stable, and forgiving.
%p
  The Eze's hull shape creates a strong platform for new paddlers to develop their technique with confidence. The ergonomics are excellent, and seat comfort outstanding. Experienced paddlers will love the quickness and maneuverability of the Eze, and be blown away by how easy and fun it is to surf. A boat that puts a smile on every face!

%h3 Prices
= render "construction", title: "eze", code: 'S-102F', euros: 2695, type: :performance
= render "construction", title: "eze", code: 'S-102R', euros: 3195, type: :river
= render "construction", title: "eze", code: 'S-102K', euros: 3495, type: :elite
= render "construction", title: "eze", code: 'S-102U', euros: 4295, type: :ultimate

app/views/skis/_ion.html.haml
%h3 Dimensions
%ul
  %li Length: 642 cm
  %li Width: 44.5 cm
  %li Capacity: 70 - 115 kg

%p The 2017 Think Ion is back as the high performance all-star! With a new rocker profile, new seat and footwell, and new low profile deck, the ion is tuned to offer great speed, handling, and efficiency.

%p Whether in a howling downwind or on the mirror flats, the Ion is a true all-conditions advanced paddler’s ski.

%p One of the very important aspects retained in this forward design is the increased stability compared to an elite ski. This increase in stability allows the paddler to apply full power, even when conditions get testing.

%p The updated seat and footwell accommodate a greater range of athlete sizes, both tall and small. The seat hump is lower improving leg drive and rotation. The lower deck lines offer less windage and reduced weight. A DeBrito bailer takes care of any water in the footwell.

%h3 Prices
= render "construction", title: "ion", code: 'S-106F', euros: 2695, type: :performance
= render "construction", title: "ion", code: 'S-106R', euros: 3195, type: :river
= render "construction", title: "ion", code: 'S-106K', euros: 3495, type: :elite
= render "construction", title: "ion", code: 'S-106U', euros: 4295, type: :ultimate

app/views/skis/_uno.html.haml
%h3 Dimensions
%ul
  %li Length: 645 cm
  %li Width: 43 cm
  %li Capacity: 50 - 90 kg

%p The Uno is the elite ski for the taller or smaller paddler that does not need the volume of the Uno Max. The new Uno is designed with lighter paddlers in mind, and has been put through it’s paces by World Champion Teneale Hatton, and U23 World Champ, Mackenzie Hynard.

%p If you want the absolute fastest ocean ski and you’re a light paddler you’ve found your match. The lower leg hump improves leg drive for shorter legged paddlers, and the reduced deck height greatly reduces windage. If you’re a bit heavier, but paddle primarily in flat to small conditions, the Uno remains an excellent choice.

%p The new Uno Max has already taken the win at the 2016 Euro Challenge, the 2016 All Wave Cup, and a podium finish at the legendary 2016 Molokai Challenge. There is simply no better all-conditions race winning craft for the elite paddler.

%h3 Prices
= render "construction", title: "uno max", code: 'S-104F', euros: 2695, type: :performance
= render "construction", title: "uno max", code: 'S-104R', euros: 3195, type: :river
= render "construction", title: "uno max", code: 'S-104K', euros: 3495, type: :elite
= render "construction", title: "uno max", code: 'S-104U', euros: 4295, type: :ultimate

app/views/skis/_uno_max.html.haml
%h3 Dimensions
%ul
  %li Length: 645 cm
  %li Width: 43 cm
  %li Capacity: 65 - 105 kg

%p Since its introduction in 2011, the Uno Max has been the boat to beat. In the five years since that first win at the Dubai Shamaal, the Uno Max has been owning the podium at events on all continents. The Euro Challenge, US Surfski Champs, Cape Point Challenge, Australian Ocean Racing Series, and World Championships are just a few of the titles she’s claimed.

%p Fast Forward to 2016; introducing the new Uno Max! Faster, improved comfort, increased stability, the 2016 Uno Max is a step forward on a proven, race-winning platform. The rocker line has 12mm added to improve glide and maneuverability in the runs, making it easier to keep the speed up and the waves linked. Seat ergonomics, already the best in class, have been engineered with more room for improved rotation and increased leg drive. The chine lines along the hull are spaced 8 mm wider, increasing stability. More stability leads to better application of power.  Small changes that add up to a significant step forward in performance.

%p The new Uno Max has already taken the win at the 2016 Euro Challenge, the 2016 All Wave Cup, and a podium finish at the legendary 2016 Molokai Challenge. There is simply no better all-conditions race winning craft for the elite paddler.

%h3 Prices
= render "construction", title: "uno max", code: 'S-104F', euros: 2695, type: :performance
= render "construction", title: "uno max", code: 'S-104R', euros: 3195, type: :river
= render "construction", title: "uno max", code: 'S-104K', euros: 3495, type: :elite
= render "construction", title: "uno max", code: 'S-104U', euros: 4295, type: :ultimate

app/views/skis/show.html.haml
- set_meta_tags title: "Think #{t(@boat, scope: [:boat, :title])}", description: t(@boat, scope: [:boat, :description])
.container.return
  = link_to root_path, class: "btn btn-default" do
    %i.fa.fa-fw.fa-arrow-left
    back

.container
  %section.boats
    %article.boat{ class: @boat }
      %h2
        %span think
        = raw t @boat, scope: [:boat, :name]
      = image_tag "#{@boat}-side.png", class: "img-responsive"
      = image_tag "#{@boat}-top.png", class: "img-responsive"

  = render @boat.sub('-', '_')

app/views/welcome/index.html.haml
.container
  %article.contact
    = image_tag "micky.jpg"
    %h2 Micky McDonald
    %p
      %i.fa.fa-fw.fa-phone
      +44 747 330 4557
    %p
      %i.fa.fa-fw.fa-envelope
      micky[at]thinkkayakeurope.com

.jumbotron
  .container
    .caption
      %h2 Think Kayaks in Europe
      %p high performance surfskis and accessories

.container
  %section.boats
    - %w[eze ace evo ion uno uno-max].each do |boat|
      %article.boat{ class: boat }
        %h2
          %span think
          = raw t boat, scope: [:boat, :name]
        = link_to ski_path(boat) do
          = image_tag "#{boat}-side.png", class: "img-responsive"
        %p= t boat, scope: [:boat, :description]

        .cta
          Find out more
          %i.fa.fa-fw.fa-arrow-right
          = link_to ski_path(boat), class: "btn btn-default" do
            %strong think
            = raw t boat, scope: [:boat, :name]